export const ROOM_STATES = [
  "WAITING",
  "SHOW-1ST-QUESTION",
  "GUESS-1ST-QUESTION",
  "ANSWER-1ST-QUESTION",
  "SHOW-2ND-QUESTION",
  "GUESS-2ND-QUESTION",
  "ANSWER-2ND-QUESTION",
  "SHOW-3RD-QUESTION",
  "GUESS-3RD-QUESTION",
  "ANSWER-3RD-QUESTION",
  "SHOW-4TH-QUESTION",
  "GUESS-4TH-QUESTION",
  "ANSWER-4TH-QUESTION",
  "WRAP UP",
] as const;

export const DEFAULT_ROOM_STATE = ROOM_STATES[0];

export type RoomState = (typeof ROOM_STATES)[number];
